USE [Rhino_Test];
TRUNCATE TABLE [Theme];

--Insert data for table "Theme".
SET IDENTITY_INSERT [Theme] ON;
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (1, 'Aquamarine', '#78DBE2');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (2, 'Blue Violet', '#7366BD');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (3, 'Tickle Me Pink Super', '#FC89AC');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (4, 'Periwinkle', '#C5D0E6');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (5, 'Tickle Me Pink', '#FC89AC');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (6, 'Yellow', '#FCE883');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (7, 'Inchworm X1', '#B2EC5D');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (8, 'Chestnut', '#BC5D58');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (9, 'Violet Red', '#F75394');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (10, 'Manatee', '#979AAA');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (11, 'Outrageous Orange X8', '#FF6E4A');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (12, 'Electric Lime Amazing', '#CEFF1D');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (13, 'Jazzberry Jam', '#CA3767');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (14, 'Brown', '#B4674D');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (15, 'Purple Mountain''s Majesty', '#9D81BA');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (16, 'Wisteria Super', '#CDA4DE');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (17, 'Blue Green', '#0D98BA');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (18, 'Manatee X2', '#979AAA');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (19, 'Tickle Me Pink (146321)', '#FC89AC');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (20, 'Unmellow Yellow X4', '#FFFF66');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (21, 'Shadow', '#8A795D');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (22, 'Wild Blue Yonder', '#A2ADD0');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (23, 'Laser Lemon', '#FEFE22');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (24, 'Red Orange Better', '#FF5349');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (25, 'Blue Bell Better', '#A2A2D0');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (26, 'Carnation Pink', '#FFAACC');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (27, 'Indigo', '#5D76CB');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (28, 'Antique Brass', '#CD9575');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (29, 'Sepia X2', '#A5694F');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (30, 'Vivid Tangerine', '#FFA089');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (31, 'Red Orange Ultra', '#FF5349');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (32, 'Goldenrod', '#FCD975');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (33, 'Yellow Professional', '#FCE883');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (34, 'Scarlet Better', '#FC2847');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (35, 'Wild Watermelon', '#FC6C85');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (36, 'Wild Strawberry', '#FF43A4');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (37, 'Red', '#EE204D');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (38, 'Olive Green', '#BAB86C');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (39, 'Blue', '#1F75FE');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (40, 'Raw Sienna', '#D68A59');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (41, 'Sunset Orange Professional', '#FD5E53');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (42, 'Macaroni and Cheese X6', '#FFBD88');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (43, 'Yellow Orange X3', '#FFAE42');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (44, 'Jazzberry Jam (780242)', '#CA3767');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (45, 'Cornflower', '#9ACEEB');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (46, 'Macaroni and Cheese Ultra', '#FFBD88');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (47, 'Gray', '#95918C');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (48, 'Wild Watermelon (858858)', '#FC6C85');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (49, 'Mahogany', '#CD4A4C');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (50, 'Laser Lemon (181786)', '#FEFE22');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (51, 'Shadow (904946)', '#8A795D');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (52, 'Silver', '#CDC5C2');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (53, 'Asparagus', '#87A96B');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (54, 'Goldenrod (520184)', '#FCD975');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (55, 'Canary', '#FFFF99');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (56, 'Cotton Candy', '#FFBCD9');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (57, 'Eggplant', '#6E5160');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (58, 'Burnt Orange Elite', '#FF7F49');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (59, 'Blue Violet Amazing', '#7366BD');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (60, 'Turquoise Blue', '#77DDE7');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (61, 'Burnt Orange Super', '#FF7F49');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (62, 'Neon Carrot', '#FFA343');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (63, 'Purple Pizzazz Super', '#FE4EDA');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (64, 'Yellow Green X1', '#C5E384');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (65, 'Laser Lemon (121387)', '#FEFE22');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (66, 'Violet', '#926EAE');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (67, 'Fuchsia', '#C364C5');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (68, 'Blush X5', '#DE5D83');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (69, 'Green Ultra', '#1CAC78');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (70, 'Purple Heart X5', '#7442C8');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (71, 'Pink Flamingo', '#FC74FD');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (72, 'Pine Green', '#158078');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (73, 'Brown (208335)', '#B4674D');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (74, 'Beaver', '#9F8170');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (75, 'Laser Lemon (564049)', '#FEFE22');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (76, 'Radical Red', '#FF496C');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (77, 'Cotton Candy (672226)', '#FFBCD9');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (78, 'Outer Space', '#414A4C');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (79, 'Outrageous Orange', '#FF6E4A');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (80, 'Mahogany (255731)', '#CD4A4C');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (81, 'Shocking Pink', '#FB7EFD');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (82, 'Blue Green (674486)', '#0D98BA');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (83, 'Magenta X6', '#F664AF');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (84, 'Timberwolf', '#DBD7D2');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (85, 'Wild Strawberry (330105)', '#FF43A4');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (86, 'Midnight Blue', '#1A4876');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (87, 'Cerise', '#DD4492');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (88, 'Eggplant Better', '#6E5160');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (89, 'Wisteria', '#CDA4DE');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (90, 'Purple Pizzazz Professional', '#FE4EDA');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (91, 'Yellow Green Ultra', '#C5E384');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (92, 'Aquamarine Professional', '#78DBE2');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (93, 'Turquoise Blue X3', '#77DDE7');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (94, 'Wild Watermelon (490543)', '#FC6C85');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (95, 'White X2', '#FFFFFF');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (96, 'Pink Flamingo (736322)', '#FC74FD');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (97, 'Spring Green Ultra', '#ECEABE');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (98, 'Burnt Orange Super (544662)', '#FF7F49');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (99, 'Vivid Tangerine Amazing', '#FFA089');
INSERT INTO [Theme] ([ID], [Name], [HexCode]) VALUES (100, 'Red (896702)', '#EE204D');
SET IDENTITY_INSERT [Theme] OFF;